### ISSUE TITLE
Exception if identity file path does not exist: i18n key errors.CHEFVAL001 does not exist.

### ISSUE THREAD

**Issue by karthanistyr** [chef/chef-apply#118]
## Description
An exception is thrown when the path passed to `-i|--identity-file` does not exist.

## Chef Apply Version
0.4.11 (possibly others)

## Platform Version
All

## Replication Case
Issue a command with parameter `-i|--identity-file` and a pass a path that does not exist.
```
$ chef-run myhost.example.com --user some-user -i ./this-path-does-not-exist recipes/my_recipe.rb
```
## Client Output
N/A

## Stacktrace
```
INTERNAL ERROR
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Message:
i18n key errors.CHEFVAL001 does not exist.
Referenced from File: chef_apply/ui/error_printer.rb Line: 71
Backtrace:
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/text/text_wrapper.rb:48:in `method_missing'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/text/error_translation.rb:32:in `initialize'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/ui/error_printer.rb:103:in `new'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/ui/error_printer.rb:103:in `initialize'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/ui/error_printer.rb:71:in `new'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/ui/error_printer.rb:71:in `write_backtrace'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/cli.rb:315:in `capture_exception_backtrace'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/cli.rb:281:in `handle_perform_error'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/cli.rb:122:in `rescue in perform_run'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/cli.rb:103:in `perform_run'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/cli.rb:72:in `block in run'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/telemeter.rb:85:in `block in timed_capture'
/opt/chef-workstation/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/telemeter.rb:85:in `timed_capture'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/telemeter.rb:74:in `timed_run_capture'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/cli.rb:70:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/startup.rb:189:in `start_chef_apply'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/startup.rb:65:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/bin/chef-run:23:in `<top (required)>'
/usr/bin/chef-run:306:in `load'
/usr/bin/chef-run:306:in `<main>'
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
```

### Relevant code
In `lib/chef_apply/cli/options.rb`
```ruby
       klass.option :identity_file,
          long: "--identity-file PATH",
          short: "-i PATH",
          description: T.identity_file,
          proc: (Proc.new do |paths|
            path = paths
            unless File.exist?(path)
              raise OptionValidationError.new("CHEFVAL001", self, path)
            end

            path
          end)
```

**Comment by afiune** [comment]
Thank you for creating this issue. We believe that we have missed the definition of this error. We will fix it and notify you.
