### ISSUE TITLE
Chef-Run on Windows host to Linux guest failure

### ISSUE THREAD

**Issue by srb3** [chef/chef-apply#129]
## Description

chef-run fails when running from a windows host to a linux guest that uses a newer OpenSSH key format.

## Chef Apply Version
 0.15.6 and 0.17.5

## Platform Version
Windows Server 2019

## Client Output
workstation 0.17.5 error
```
PS C:\Users\chef\Desktop\workspace\src\sandbox\populate> chef-run ssh://chef@some-ip files/my_cookbook --identity-file C:\Users\chef\.ssh\server.pem --chef-license accept
 [✔] Packaging cookbook... done!
 [✔] Generating local policyfile... exporting... done!
 [/] Applying builder_populate::default from C:/Users/chef/Desktop/workspace/src/sandbox/populate/files/builder_populate to target.
 |__ [/] [104.214.238.10] Connecting as chef...
INTERNAL ERROR
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Message:
OpenSSH keys only supported if ED25519 is available
net-ssh requires the following gems for ed25519 support:
 * ed25519 (>= 1.2, < 2.0)
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
LoadError : "cannot load such file -- bcrypt_pbkdf_ext"
Backtrace:
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/ed25519_loader.rb:21:in `raiseUnlessLoaded'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:202:in `classify_key'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:53:in `load_data_private_key'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:44:in `load_private_key'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:232:in `block in load_identities'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:225:in `map'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:225:in `load_identities'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:101:in `each_identity'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `each'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `authenticate'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:250:in `start'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/transports/ssh_connection.rb:185:in `establish_connection'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/transports/ssh_connection.rb:254:in `session'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/transports/ssh_connection.rb:223:in `run_command_via_connection'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/plugins/base_connection.rb:128:in `run_command'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/platforms/detect/helpers/os_windows.rb:9:in `check_cmd'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/platforms/detect/helpers/os_windows.rb:4:in `detect_windows'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/platforms/detect/specifications/os.rb:29:in `block in load'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/platforms/detect/scanner.rb:46:in `instance_eval'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/platforms/detect/scanner.rb:46:in `block in scan_children'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/platforms/detect/scanner.rb:45:in `each'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/platforms/detect/scanner.rb:45:in `scan_children'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/platforms/detect/scanner.rb:33:in `block in scan'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/platforms/detect/scanner.rb:27:in `each'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/platforms/detect/scanner.rb:27:in `scan'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/platforms/detect.rb:9:in `scan'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/plugins/base_connection.rb:116:in `platform'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/extras/command_wrapper.rb:166:in `load'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/transports/ssh_connection.rb:53:in `initialize'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/transports/ssh.rb:240:in `new'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/transports/ssh.rb:240:in `create_new_connection'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.2.0/lib/train/transports/ssh.rb:82:in `connection'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.15/lib/chef_apply/target_host.rb:118:in `connect!'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.15/lib/chef_apply/cli.rb:332:in `do_connect'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.15/lib/chef_apply/cli.rb:178:in `connect_target'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.15/lib/chef_apply/cli.rb:163:in `block (2 levels) in render_converge'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.15/lib/chef_apply/ui/terminal/job.rb:31:in `run'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.15/lib/chef_apply/ui/terminal.rb:60:in `block (2 levels) in render_parallel_jobs'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/tty-spinner-0.9.3/lib/tty/spinner.rb:225:in `execute_job'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/tty-spinner-0.9.3/lib/tty/spinner/multi.rb:150:in `block (2 levels) in auto_spin'
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
PS C:\Users\chef\Desktop\workspace\src\sandbox\populate> chef --version
Chef Workstation version: 0.17.5
Chef Infra Client version: 15.8.23
Chef InSpec version: 4.18.100
Chef CLI version: 2.0.0
Test Kitchen version: 2.4.0
Cookstyle version: 5.22.6
```

no stack-trace.log
```
PS C:\Users\chef\Desktop\workspace\src\sandbox\populate> cat C:\opscode\chef-workstation\gem-version-manifest.json| egrep -e 'ed25519|bcrypt_pbkdf'
  "bcrypt_pbkdf": [
  "ed25519": [
```

**Comment by marcparadise** [comment]
While the necessary gems are packaged (bcrypt_pbkdf and ed25519) and installed, the Windows build does not have the bcrypt_pbkdf native extension build.

This is leading to the error seen in the stack: 

`LoadError : "cannot load such file -- bcrypt_pbkdf_ext`

**Comment by marcparadise** [comment]
A little more digging showed that while the ruby 2.0-2.3 extensions were included by default, an explicit gem build is required to ensure that the extension is built for the current ruby library -- the 'gem install' we did by default was not sufficient since that we include the default 2.0-2.3 libs on windows. 

Adding a software component  definition for the bcrypt_pbkdf-ruby package and building it before the `gems` component is built resolves the issue by a) ensuring that the gem has the correct extension on windows, and b) gets picked up by the `gems` component so that the built gem is used during `bundle install`.
