### ISSUE TITLE
Unexpected 404 trying to load policyfile

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-apply#30]
## Description
See stack trace

## Chef Apply Version
master

## Platform Version
host - mac
target - ubuntu and Windows

## Replication Case
Not sure yet - tried `chef-client ubuntu1 test-workstation4` and that cookbook has a dependency on another local cookbook `test-workstation2`. It worked at first then started failing with this 404

## Stacktrace
From chef client on target:
```
Generated at 2018-07-27 17:15:29 +0000
Chef::PolicyBuilder::Policyfile::ConfigurationError: Error loading policyfile from `policy_groups/local/policies/test-workstation4_policy': Net::HTTPServerException - 404 "Not Found"
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/policy_builder/policyfile.rb:298:in `rescue in policy'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/policy_builder/policyfile.rb:295:in `policy'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/policy_builder/policyfile.rb:290:in `run_list'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/policy_builder/policyfile.rb:318:in `validate_policyfile'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/policy_builder/policyfile.rb:141:in `finish_load_node'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/policy_builder/dynamic.rb:75:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/client.rb:470:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/client.rb:270:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/application.rb:292:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/application.rb:280:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/application.rb:280:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/application.rb:245:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/application.rb:233:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/application/client.rb:470:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/application/client.rb:459:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/application/client.rb:458:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/application/client.rb:458:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/application/client.rb:442:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:75:in `load'
/usr/bin/chef-client:75:in `<main>'
```

**Comment by tyler-ball** [comment]
We need to go confirm this is still an issue in the latest version of the package.
